name: todo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  mobx: ^1.0.1
  flutter_mobx: ^1.0.1
  provider: ^4.0.4
  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  hive_generator: ^0.7.0
  path_provider: ^1.6.0
  uuid: ^2.0.4
  grouped_buttons: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  mobx_codegen: ^1.0.1

flutter:
  uses-material-design: true
